mmo/board/urls.py
from django.urls import path
from django.shortcuts import redirect

from .views import Index, CreatePost, PostItem, EditPost, DeletePost, Responses, Respond, response_accept, \
    response_delete

app_name = 'mmo_board'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('post/<int:pk>', PostItem.as_view(), name='item'),
    path('create_ad', CreatePost.as_view(), name='create_ad'),
    path('post/<int:pk>/edit', EditPost.as_view()),
    path('post/<int:pk>/delete', DeletePost.as_view()),
    path('responses', Responses.as_view(), name='responses'),
    path('responses/<int:pk>', Responses.as_view(), name='responses'),
    path('respond/<int:pk>', Respond.as_view(), name='respond'),
    path('response/accept/<int:pk>', response_accept),
    path('response/delete/<int:pk>', response_delete),

]

mmo/mmo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

mmo/board/models.py
from django.db import models
from django.contrib.auth.models import User


class Ads(models.Model):
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    CAT = (('tanks', 'Танки'),
           ('healers', 'Хилы'),
           ('damage_dealers', 'ДД'),
           ('dealers', 'Торговцы'),
           ('gildmasters', 'Гилдмастеры'),
           ('quest_givers', 'Квестгиверы'),
           ('blacksmiths', 'Кузнецы'),
           ('tanners', 'Кожевники'),
           ('potion_makers', 'Зельевары'),
           ('spell_masters', 'Мастера заклинаний'))
    category = models.CharField(
        max_length=15, choices=CAT, verbose_name='Категория')
    dateCreation = models.DateField(auto_now_add=True, verbose_name='Создано')
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')

    class Meta:
        verbose_name = ("Объявление")
        verbose_name_plural = ("Объявления")

    def __str__(self):
        return self.name


class Response(models.Model):
    player = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Игрок')
    post = models.ForeignKey(
        Ads, on_delete=models.CASCADE, verbose_name='Объявление')
    text = models.TextField(verbose_name='Текст')
    status = models.BooleanField(default=False, verbose_name='Статус')
    dateCreation = models.DateTimeField(
        auto_now_add=True, verbose_name='Создано')

mmo/templates/add.html
{% extends 'flatpages/default.html' %}

{% load static %}


{% block content %}
    <br>
    <h3>Новое объявление</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
       <div class="text-white">
            {{ form.media }}
            {{ form.as_p }}
       </div>
		<input class="btn btn-secondary" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

mmo/templates/ads.html
{% extends 'flatpages/default.html' %}

{% load static %}


{{% block title %}Ads{% endblock title %}

{% block content %}
    <br><br>
    {% if posts %}
        {% for post in posts %}
            <a href="/post/{{ post.id }}" style="font-size: 20px;"><b><a href="{% url 'mmo_board:item' post.id%}">{{ post.title }}</a></b></a><br>
            <span style="font-size: 12px;"><b>Автор:  {{ post.author }} |
                 {{ post.dateCreation|date:'d.M.Y' }} г.</b></span><br><br>

        {% endfor %}
    {% else %}
        <br><br>
        <h2>Публикаций нет!</h2>
    {% endif %}

    {% if user.is_authenticated %}
        <br><br><br>
        <a class="btn btn-secondary" href="{% url 'mmo_board:create_ad' %}" role="button">Добавить новое объявление</a>
    {% endif %}
{% endblock content %}

mmo/templates/dell.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block title %}Del{% endblock title %}

{% block content %}
    <br>
    <h3>Удалиль объявления:</h3><br>

    {% autoescape off %}
    <h2>{{ post.title }}</h2>
    <span>{{ post.text }}<br></span>
    {% endautoescape %}
    <hr>

    <span>{{ post.dateCreation|date:'d-M-Y f' }}, ({{ post.author }})</span><br>
    <span>Категория: {{ post.get_category_display }}</span>

    <br><br>

    <h4>Вы действительно хотите удалить?:</h4>
    <form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-secondary" style="background: red" value="подтвердить"></form>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

mmo/templates/edit.html
{% extends 'flatpages/default.html' %}

{% load static %}


{% block title %}Edit{% endblock title %}
{% load static %}

{% block content %}
    <br>
    <h3>Редактирование объявления:</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
		<input class="btn btn-secondary" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

mmo/templates/item.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block title %}Ad{% endblock title %}

{% block content %}
    <br><br>
    {% autoescape off %}
    <h2>{{ post.title }}</h2><br>
    <span>{{ post.text }}<br></span>
    {% endautoescape %}
    <hr>
    <span>Автор: {{ post.author }}</span>
    <span>| Категория: {{ post.get_category_display }}</span>
    <span>|{{ post.dateCreation|date:'d-M-Y f' }}</span>

    <br><br>

    <a class="btn btn-secondary" href="{% url 'index' %}" role="button">Закрыть</a>
    <a class="btn btn-secondary" href="/post/{{ post.id }}/edit" role="button">Редактировать</a>
    <a class="btn btn-secondary" href="/post/{{ post.id }}/delete" role="button">Удалить</a>

    {% if user.is_authenticated %}
    <br><br>
        {% if respond == "Ответить" %}
            <a style="color:red">Вы ответили на это объевление.</a><br>
            <a href="{% url 'responses' %}">Посмотреть свои отклики</a>
        {% elif respond == "Мое_объявление" %}
            <a style="color:red">Вы не можете ответить на свое объявление.</a><br>
        {% else %}
            <a class="btn btn-secondary" href="/respond/{{ post.id }}" role="button">Ответить</a>
        {% endif %}
    {% endif %}
    <br><br>
{% endblock content %}

mmo/templates/respond.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Respond{% endblock title %}
{% load static %}

{% block content %}
    <br>
    <h3>Текст отклика:</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		<input class="btn btn-secondary" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

mmo/templates/responses.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block content %}
    <br>
    <h3>Фильтр откликов на мои объявления:</h3><br>
	<form method="POST">
		{% csrf_token %}
        {{ form }}
		<input class="btn btn-secondary" type="submit" value="Показать">
	</form><br>
    {% if title %}
        <h3>Oтклики на мое объявление</h3>
        <a href="/post/{{ response_post_id }}" style="font-size: 20px;"><b>{{ title }}:</b></a><br>
        {% if filter_responses %}
            {% for response in filter_responses %}
                <a><b>Отклик: </b></a>{{ response.text }}<br>
                <span style="font-size: 12px;"><b>Автор отклика: {{ response.author.username }} |
                    дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
                {% if response.status == False %}
                    <a href="/response/accept/{{ response.id }}" style="font-size: 12px; color:green"><b>принять</b></a>
                    <a>&nbsp;&nbsp;&nbsp;</a>
                    <a href="/response/delete/{{ response.id }}" style="font-size: 12px; color:red"><b>удалить</b></a>
                {% else %}
                    <a style="font-size: 14px; color:green"><b>отклик принят</b></a>
                {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <br>
            <h5>Откликов нет!</h5>
        {% endif %}
    {% else %}
        <h3>Oтклики на все мои объявления:</h3>
        {% if filter_responses %}
            {% for response in filter_responses %}
                <a><b>Объявление:</b></a>
                <a href="/post/{{ response.post_id }}" style="font-size: 20px;"><b>{{ response.post.title }}</b></a><br>
                <span style="font-size: 12px;"><b>Дата публикации объявления: {{ response.post.dateCreation|date:'d.M.Y' }} г.</b>
                </span><br>
                <a><b>Отклик: </b></a>{{ response.text }}<br>
                <span style="font-size: 12px;"><b>Автор отклика: {{ response.author.username }} |
                    дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
                {% if response.status == False %}
                    <a href="/response/accept/{{ response.id }}" style="font-size: 12px; color:green"><b>принять</b></a>
                    <a>&nbsp;&nbsp;&nbsp;</a>
                    <a href="/response/delete/{{ response.id }}" style="font-size: 12px; color:red"><b>удалить</b></a>
                {% else %}
                    <a style="font-size: 14px; color:green"><b>отклик принят</b></a>
                {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <h5>Откликов нет!</h5>
        {% endif %}
    {% endif %}
    <br><br>
    <h3>Мои отклики на объявления:</h3>
    {% if myresponses %}
        {% for response in myresponses %}
            <a><b>Объявление:</b></a>
            <a href="/post/{{ response.post_id }}" style="font-size: 20px;"><b>{{ response.post.title }}</b></a><br>
            <span style="font-size: 12px;"><b>Автор объявления:  {{ response.post.author.username }} |
                дата публикации объявления: {{ response.post.dateCreation|date:'d.M.Y' }} г.</b></span><br>
            <a><b>Мой отклик:</b></a>
            {{ response.text }}<br>
            <span style="font-size: 12px;"><b>Дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
            {% if response.status == True %}
                <a style="font-size: 14px; color:green"><b>Автор объявления принял отклик!</b></a>
            {% else %}
                <a style="font-size: 14px; color:red"><b>Автор объявления пока не принял отклик!</b></a>
            {% endif %}
        <br><br>
        {% endfor %}
    {% else %}
        <h5>Откликов нет!</h5>
    {% endif %}
{% endblock content %}